# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mlsimInterfaceMsgs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mlsimInterfaceMsgs.proto',
  package='mlsimInterfaceMsgs',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x18mlsimInterfaceMsgs.proto\x12\x12mlsimInterfaceMsgs\"\xa4\x03\n\x15MlSimInterfaceMessage\x12\x13\n\x0bmessageType\x18\x01 \x01(\x05\x12\x36\n\x0binitRequest\x18\x02 \x01(\x0b\x32\x1f.mlsimInterfaceMsgs.InitRequestH\x00\x12\x38\n\x0cinitResponse\x18\x03 \x01(\x0b\x32 .mlsimInterfaceMsgs.InitResponseH\x00\x12<\n\x0esimStepRequest\x18\x04 \x01(\x0b\x32\".mlsimInterfaceMsgs.SimStepRequestH\x00\x12>\n\x0fsimStepResponse\x18\x05 \x01(\x0b\x32#.mlsimInterfaceMsgs.SimStepResponseH\x00\x12\x38\n\x0cmsgTxRequest\x18\x06 \x01(\x0b\x32 .mlsimInterfaceMsgs.MsgTxRequestH\x00\x12:\n\rmsgTxResponse\x18\x07 \x01(\x0b\x32!.mlsimInterfaceMsgs.MsgTxResponseH\x00\x42\x10\n\x0eMessagePayload\"\"\n\x0bInitRequest\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\"M\n\x0cInitResponse\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x12\n\nclientName\x18\x02 \x01(\t\x12\x14\n\x0cmobileNodeId\x18\x03 \x01(\t\"D\n\x0eSimStepRequest\x12\x12\n\nclientName\x18\x01 \x01(\t\x12\r\n\x05round\x18\x02 \x01(\x05\x12\x0f\n\x07simTime\x18\x03 \x01(\x02\"J\n\x0fSimStepResponse\x12\x12\n\nclientName\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"7\n\x0cMsgTxRequest\x12\x12\n\nclientName\x18\x01 \x01(\t\x12\x13\n\x0bmessageSize\x18\x03 \x01(\x05\"D\n\rMsgTxResponse\x12\x12\n\nclientName\x18\x01 \x01(\t\x12\x0f\n\x07simTime\x18\x02 \x01(\x02\x12\x0e\n\x06status\x18\x03 \x01(\x05*\xa7\x01\n\x0b\x43ommandType\x12\r\n\tCMD_ERROR\x10\x00\x12\x14\n\x10\x43MD_SIM_STEP_REQ\x10\x01\x12\x14\n\x10\x43MD_SIM_STEP_RSP\x10\x02\x12\x11\n\rCMD_TERMINATE\x10\x03\x12\x10\n\x0c\x43MD_INIT_REQ\x10\x04\x12\x10\n\x0c\x43MD_INIT_RSP\x10\x05\x12\x12\n\x0e\x43MD_MSG_TX_REQ\x10\x06\x12\x12\n\x0e\x43MD_MSG_TX_RSP\x10\x07\x62\x06proto3')
)

_COMMANDTYPE = _descriptor.EnumDescriptor(
  name='CommandType',
  full_name='mlsimInterfaceMsgs.CommandType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CMD_ERROR', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CMD_SIM_STEP_REQ', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CMD_SIM_STEP_RSP', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CMD_TERMINATE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CMD_INIT_REQ', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CMD_INIT_RSP', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CMD_MSG_TX_REQ', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CMD_MSG_TX_RSP', index=7, number=7,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=860,
  serialized_end=1027,
)
_sym_db.RegisterEnumDescriptor(_COMMANDTYPE)

CommandType = enum_type_wrapper.EnumTypeWrapper(_COMMANDTYPE)
CMD_ERROR = 0
CMD_SIM_STEP_REQ = 1
CMD_SIM_STEP_RSP = 2
CMD_TERMINATE = 3
CMD_INIT_REQ = 4
CMD_INIT_RSP = 5
CMD_MSG_TX_REQ = 6
CMD_MSG_TX_RSP = 7



_MLSIMINTERFACEMESSAGE = _descriptor.Descriptor(
  name='MlSimInterfaceMessage',
  full_name='mlsimInterfaceMsgs.MlSimInterfaceMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageType', full_name='mlsimInterfaceMsgs.MlSimInterfaceMessage.messageType', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='initRequest', full_name='mlsimInterfaceMsgs.MlSimInterfaceMessage.initRequest', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='initResponse', full_name='mlsimInterfaceMsgs.MlSimInterfaceMessage.initResponse', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='simStepRequest', full_name='mlsimInterfaceMsgs.MlSimInterfaceMessage.simStepRequest', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='simStepResponse', full_name='mlsimInterfaceMsgs.MlSimInterfaceMessage.simStepResponse', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msgTxRequest', full_name='mlsimInterfaceMsgs.MlSimInterfaceMessage.msgTxRequest', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msgTxResponse', full_name='mlsimInterfaceMsgs.MlSimInterfaceMessage.msgTxResponse', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='MessagePayload', full_name='mlsimInterfaceMsgs.MlSimInterfaceMessage.MessagePayload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=49,
  serialized_end=469,
)


_INITREQUEST = _descriptor.Descriptor(
  name='InitRequest',
  full_name='mlsimInterfaceMsgs.InitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='mlsimInterfaceMsgs.InitRequest.description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=471,
  serialized_end=505,
)


_INITRESPONSE = _descriptor.Descriptor(
  name='InitResponse',
  full_name='mlsimInterfaceMsgs.InitResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='mlsimInterfaceMsgs.InitResponse.description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clientName', full_name='mlsimInterfaceMsgs.InitResponse.clientName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mobileNodeId', full_name='mlsimInterfaceMsgs.InitResponse.mobileNodeId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=507,
  serialized_end=584,
)


_SIMSTEPREQUEST = _descriptor.Descriptor(
  name='SimStepRequest',
  full_name='mlsimInterfaceMsgs.SimStepRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientName', full_name='mlsimInterfaceMsgs.SimStepRequest.clientName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='round', full_name='mlsimInterfaceMsgs.SimStepRequest.round', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='simTime', full_name='mlsimInterfaceMsgs.SimStepRequest.simTime', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=586,
  serialized_end=654,
)


_SIMSTEPRESPONSE = _descriptor.Descriptor(
  name='SimStepResponse',
  full_name='mlsimInterfaceMsgs.SimStepResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientName', full_name='mlsimInterfaceMsgs.SimStepResponse.clientName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='mlsimInterfaceMsgs.SimStepResponse.status', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='mlsimInterfaceMsgs.SimStepResponse.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=656,
  serialized_end=730,
)


_MSGTXREQUEST = _descriptor.Descriptor(
  name='MsgTxRequest',
  full_name='mlsimInterfaceMsgs.MsgTxRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientName', full_name='mlsimInterfaceMsgs.MsgTxRequest.clientName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='messageSize', full_name='mlsimInterfaceMsgs.MsgTxRequest.messageSize', index=1,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=732,
  serialized_end=787,
)


_MSGTXRESPONSE = _descriptor.Descriptor(
  name='MsgTxResponse',
  full_name='mlsimInterfaceMsgs.MsgTxResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientName', full_name='mlsimInterfaceMsgs.MsgTxResponse.clientName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='simTime', full_name='mlsimInterfaceMsgs.MsgTxResponse.simTime', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='mlsimInterfaceMsgs.MsgTxResponse.status', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=789,
  serialized_end=857,
)

_MLSIMINTERFACEMESSAGE.fields_by_name['initRequest'].message_type = _INITREQUEST
_MLSIMINTERFACEMESSAGE.fields_by_name['initResponse'].message_type = _INITRESPONSE
_MLSIMINTERFACEMESSAGE.fields_by_name['simStepRequest'].message_type = _SIMSTEPREQUEST
_MLSIMINTERFACEMESSAGE.fields_by_name['simStepResponse'].message_type = _SIMSTEPRESPONSE
_MLSIMINTERFACEMESSAGE.fields_by_name['msgTxRequest'].message_type = _MSGTXREQUEST
_MLSIMINTERFACEMESSAGE.fields_by_name['msgTxResponse'].message_type = _MSGTXRESPONSE
_MLSIMINTERFACEMESSAGE.oneofs_by_name['MessagePayload'].fields.append(
  _MLSIMINTERFACEMESSAGE.fields_by_name['initRequest'])
_MLSIMINTERFACEMESSAGE.fields_by_name['initRequest'].containing_oneof = _MLSIMINTERFACEMESSAGE.oneofs_by_name['MessagePayload']
_MLSIMINTERFACEMESSAGE.oneofs_by_name['MessagePayload'].fields.append(
  _MLSIMINTERFACEMESSAGE.fields_by_name['initResponse'])
_MLSIMINTERFACEMESSAGE.fields_by_name['initResponse'].containing_oneof = _MLSIMINTERFACEMESSAGE.oneofs_by_name['MessagePayload']
_MLSIMINTERFACEMESSAGE.oneofs_by_name['MessagePayload'].fields.append(
  _MLSIMINTERFACEMESSAGE.fields_by_name['simStepRequest'])
_MLSIMINTERFACEMESSAGE.fields_by_name['simStepRequest'].containing_oneof = _MLSIMINTERFACEMESSAGE.oneofs_by_name['MessagePayload']
_MLSIMINTERFACEMESSAGE.oneofs_by_name['MessagePayload'].fields.append(
  _MLSIMINTERFACEMESSAGE.fields_by_name['simStepResponse'])
_MLSIMINTERFACEMESSAGE.fields_by_name['simStepResponse'].containing_oneof = _MLSIMINTERFACEMESSAGE.oneofs_by_name['MessagePayload']
_MLSIMINTERFACEMESSAGE.oneofs_by_name['MessagePayload'].fields.append(
  _MLSIMINTERFACEMESSAGE.fields_by_name['msgTxRequest'])
_MLSIMINTERFACEMESSAGE.fields_by_name['msgTxRequest'].containing_oneof = _MLSIMINTERFACEMESSAGE.oneofs_by_name['MessagePayload']
_MLSIMINTERFACEMESSAGE.oneofs_by_name['MessagePayload'].fields.append(
  _MLSIMINTERFACEMESSAGE.fields_by_name['msgTxResponse'])
_MLSIMINTERFACEMESSAGE.fields_by_name['msgTxResponse'].containing_oneof = _MLSIMINTERFACEMESSAGE.oneofs_by_name['MessagePayload']
DESCRIPTOR.message_types_by_name['MlSimInterfaceMessage'] = _MLSIMINTERFACEMESSAGE
DESCRIPTOR.message_types_by_name['InitRequest'] = _INITREQUEST
DESCRIPTOR.message_types_by_name['InitResponse'] = _INITRESPONSE
DESCRIPTOR.message_types_by_name['SimStepRequest'] = _SIMSTEPREQUEST
DESCRIPTOR.message_types_by_name['SimStepResponse'] = _SIMSTEPRESPONSE
DESCRIPTOR.message_types_by_name['MsgTxRequest'] = _MSGTXREQUEST
DESCRIPTOR.message_types_by_name['MsgTxResponse'] = _MSGTXRESPONSE
DESCRIPTOR.enum_types_by_name['CommandType'] = _COMMANDTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MlSimInterfaceMessage = _reflection.GeneratedProtocolMessageType('MlSimInterfaceMessage', (_message.Message,), dict(
  DESCRIPTOR = _MLSIMINTERFACEMESSAGE,
  __module__ = 'mlsimInterfaceMsgs_pb2'
  # @@protoc_insertion_point(class_scope:mlsimInterfaceMsgs.MlSimInterfaceMessage)
  ))
_sym_db.RegisterMessage(MlSimInterfaceMessage)

InitRequest = _reflection.GeneratedProtocolMessageType('InitRequest', (_message.Message,), dict(
  DESCRIPTOR = _INITREQUEST,
  __module__ = 'mlsimInterfaceMsgs_pb2'
  # @@protoc_insertion_point(class_scope:mlsimInterfaceMsgs.InitRequest)
  ))
_sym_db.RegisterMessage(InitRequest)

InitResponse = _reflection.GeneratedProtocolMessageType('InitResponse', (_message.Message,), dict(
  DESCRIPTOR = _INITRESPONSE,
  __module__ = 'mlsimInterfaceMsgs_pb2'
  # @@protoc_insertion_point(class_scope:mlsimInterfaceMsgs.InitResponse)
  ))
_sym_db.RegisterMessage(InitResponse)

SimStepRequest = _reflection.GeneratedProtocolMessageType('SimStepRequest', (_message.Message,), dict(
  DESCRIPTOR = _SIMSTEPREQUEST,
  __module__ = 'mlsimInterfaceMsgs_pb2'
  # @@protoc_insertion_point(class_scope:mlsimInterfaceMsgs.SimStepRequest)
  ))
_sym_db.RegisterMessage(SimStepRequest)

SimStepResponse = _reflection.GeneratedProtocolMessageType('SimStepResponse', (_message.Message,), dict(
  DESCRIPTOR = _SIMSTEPRESPONSE,
  __module__ = 'mlsimInterfaceMsgs_pb2'
  # @@protoc_insertion_point(class_scope:mlsimInterfaceMsgs.SimStepResponse)
  ))
_sym_db.RegisterMessage(SimStepResponse)

MsgTxRequest = _reflection.GeneratedProtocolMessageType('MsgTxRequest', (_message.Message,), dict(
  DESCRIPTOR = _MSGTXREQUEST,
  __module__ = 'mlsimInterfaceMsgs_pb2'
  # @@protoc_insertion_point(class_scope:mlsimInterfaceMsgs.MsgTxRequest)
  ))
_sym_db.RegisterMessage(MsgTxRequest)

MsgTxResponse = _reflection.GeneratedProtocolMessageType('MsgTxResponse', (_message.Message,), dict(
  DESCRIPTOR = _MSGTXRESPONSE,
  __module__ = 'mlsimInterfaceMsgs_pb2'
  # @@protoc_insertion_point(class_scope:mlsimInterfaceMsgs.MsgTxResponse)
  ))
_sym_db.RegisterMessage(MsgTxResponse)


# @@protoc_insertion_point(module_scope)
